'use strict';

// ─── Authentication ───
const SESSION_DURATION_HOURS = 72;
const COOKIE_NAME = 'cw_session';
const MAX_LOGIN_ATTEMPTS = 5;
const LOCKOUT_MINUTES = 15;
const USERNAME_PATTERN = /^[a-zA-Z0-9_.-]{3,50}$/;

// ─── Password Hashing (db.js) ───
const AUTH_PBKDF2_ITERATIONS = 100000;
const AUTH_PBKDF2_KEY_LENGTH = 64;
const AUTH_PBKDF2_DIGEST = 'sha512';

// ─── Connection Encryption (encryption.js) ───
const ENCRYPTION_ALGORITHM = 'aes-256-gcm';
const ENCRYPTION_KEY_LENGTH = 32;
const ENCRYPTION_IV_LENGTH = 16;
const ENCRYPTION_SALT_LENGTH = 64;
const ENCRYPTION_PBKDF2_ITERATIONS = 100000;
const ENCRYPTION_PBKDF2_DIGEST = 'sha256';

// ─── Server ───
const EXPORT_CACHE_TTL = 3600;
const SHUTDOWN_TIMEOUT_MS = 10000;

// ─── WebSocket / Sockets ───
const SOCKET_KEEPALIVE_MS = 300000;
const SOCKET_TIMEOUT_MS = 30000;
const SOCKET_ERROR_EVENTS = ['error', 'close', 'timeout', 'parseError'];

module.exports = {
  SESSION_DURATION_HOURS,
  COOKIE_NAME,
  MAX_LOGIN_ATTEMPTS,
  LOCKOUT_MINUTES,
  USERNAME_PATTERN,
  AUTH_PBKDF2_ITERATIONS,
  AUTH_PBKDF2_KEY_LENGTH,
  AUTH_PBKDF2_DIGEST,
  ENCRYPTION_ALGORITHM,
  ENCRYPTION_KEY_LENGTH,
  ENCRYPTION_IV_LENGTH,
  ENCRYPTION_SALT_LENGTH,
  ENCRYPTION_PBKDF2_ITERATIONS,
  ENCRYPTION_PBKDF2_DIGEST,
  EXPORT_CACHE_TTL,
  SHUTDOWN_TIMEOUT_MS,
  SOCKET_KEEPALIVE_MS,
  SOCKET_TIMEOUT_MS,
  SOCKET_ERROR_EVENTS,
};
